# model url
websocket.modelServer.url=ws://localhost:8765
# web_url
web.url=*
websocket.webUser.url=/topic/face_fatigue/
websocket.videoUser.url=/topic/face_video/
spring.application.name=faceservice
server.port=8081
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
server.ssl.enabled=false
